DROP TABLE IF EXISTS customer;

CREATE TABLE CUSTOMER(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	ic VARCHAR(20) NOT NULL,
	date_of_birth DATE NOT NULL,
	address VARCHAR(255) NOT NULL,
	address_country VARCHAR(50) NOT NULL,
	address_postcode VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
)